package com.servlet;

import com.dao.ReservationDAO;
import com.model.Reservation;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/AddReservationServlet")
public class AddReservationServlet extends HttpServlet {
    private ReservationDAO reservationDAO = new ReservationDAO();

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        // Get form data
        String customerName = request.getParameter("customerName");
        String roomNumber = request.getParameter("roomNumber");
        String checkInStr = request.getParameter("checkIn");
        String checkOutStr = request.getParameter("checkOut");
        String totalAmountStr = request.getParameter("totalAmount");

        // Input Validation
        if (customerName == null || customerName.trim().isEmpty()) {
            request.setAttribute("error", "Customer name is required");
            request.getRequestDispatcher("reservationadd.jsp").forward(request, response);
            return;
        }
        
        if (roomNumber == null || roomNumber.trim().isEmpty()) {
            request.setAttribute("error", "Room number is required");
            request.getRequestDispatcher("reservationadd.jsp").forward(request, response);
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date checkIn = sdf.parse(checkInStr);
            Date checkOut = sdf.parse(checkOutStr);
            double totalAmount = Double.parseDouble(totalAmountStr);

            // Validate dates
            if (checkOut.before(checkIn) || checkOut.equals(checkIn)) {
                request.setAttribute("error", "Check-out date must be after check-in date");
                request.getRequestDispatcher("reservationadd.jsp").forward(request, response);
                return;
            }

            // Validate amount
            if (totalAmount <= 0) {
                request.setAttribute("error", "Total amount must be positive");
                request.getRequestDispatcher("reservationadd.jsp").forward(request, response);
                return;
            }

            // Create Reservation object (ID is auto-generated, so pass 0)
            Reservation reservation = new Reservation();
            reservation.setCustomerName(customerName);
            reservation.setRoomNumber(roomNumber);
            reservation.setCheckIn(checkIn);
            reservation.setCheckOut(checkOut);
            reservation.setTotalAmount(totalAmount);

            // Save to database (ID will be auto-generated by MySQL)
            boolean success = reservationDAO.addReservation(reservation);

            if (success) {
                // Get the auto-generated ID to show in success message
                int newId = reservationDAO.getLastInsertedId();
                response.sendRedirect("DisplayReservationsServlet?message=Reservation #" + newId + " added successfully!");
            } else {
                request.setAttribute("error", "Database error: Could not add reservation");
                request.getRequestDispatcher("reservationadd.jsp").forward(request, response);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            request.setAttribute("error", "Invalid input: " + e.getMessage());
            request.getRequestDispatcher("reservationadd.jsp").forward(request, response);
        }
    }
}